# Generated by Django 4.0.6 on 2024-06-03 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='data_Postada',
            new_name='data_postada',
        ),
        migrations.AlterField(
            model_name='article',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='artigos.author'),
        ),
    ]
